name: Release Packer

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package and Upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPO_NAME=${{ github.event.repository.name }}
          TAG_NAME=${{ github.event.release.tag_name }}
          if [ -z "$TAG_NAME" ]; then
            TAG_NAME=$(git describe --tags `git rev-list --tags --max-count=1`)
          fi

          zip -r "${REPO_NAME}.zip" . -x "LICENSE" "README.md" ".git*" ".github*"
          gh release upload "$TAG_NAME" "${REPO_NAME}.zip" --clobber
          echo "Download URL: https://github.com/${{ github.repository }}/releases/latest/download/${REPO_NAME}.zip"

      - name: Update latest branch
        run: |
          git config --global user.name "github-actions[bot]" && git config --global user.email "github-actions[bot]@users.noreply.github.com"
          TAG_NAME=${{ github.event.release.tag_name }}
          if [ -z "$TAG_NAME" ]; then
            TAG_NAME=$(git describe --tags `git rev-list --tags --max-count=1`)
          fi
          
          git checkout latest || git checkout -b latest
          git reset --hard "$TAG_NAME"
          git push origin latest --force
